### ISSUE TITLE
Tracking issue for rust-url 2.0

### ISSUE THREAD

**Issue by SimonSapin** [servo/rust-url#463]
For a while now we’ve been discussing some possible breaking changes and I’ve been reluctant, to avoid dealing with moving [the ecosystem](https://crates.io/crates/url/reverse_dependencies) to a semver-incompatible version. However it’s probably time to do it anyway, in particular to get serde 1.0 support in the `url` crate itself. To avoid doing *multiple* such migrations, it would be nice batch breaking changes together.

# This is blocked on

* [x] Having a viable migration path for Servo

  * [x] Upgrading Servo from Hyper 0.11 (which uses rust-url 1.x) https://github.com/servo/servo/issues/19825
  * [ ] Upgrading https://crates.io/crates/webdriver
  * [ ] Upgrading https://crates.io/crates/ws
  * [x] Ideally we would demonstrate building Servo with a `v2.0` branch of rust-url before publishing rust-url 2.0.0 to crates.io.

# This would unblock

* [x] Removing `serde_url`
  * [x] Closing https://github.com/servo/rust-url/pull/386
  * [x] Closing https://github.com/servo/rust-url/issues/420
* [x] Closing https://github.com/servo/rust-url/pull/446
* [ ] https://github.com/servo/servo/issues/20412

# Changes to consider

Not necessarily blockers for 2.0.0.

## Update with current spec and tests

… because this might lead to API or behavior changes. 

* [ ] https://github.com/servo/rust-url/issues/163
* [ ] https://github.com/servo/rust-url/issues/290

## Breaking API changes

* [ ] https://github.com/servo/rust-url/issues/299
* [x] https://github.com/servo/rust-url/issues/304 / https://github.com/servo/rust-url/issues/303
* [ ] Rename `Url::join`? https://github.com/servo/rust-url/issues/333
* [ ] https://github.com/servo/rust-url/issues/375
* [ ] https://github.com/servo/rust-url/pull/380 / https://github.com/servo/rust-url/issues/363
* [x] https://github.com/servo/rust-url/issues/388
* [x] https://github.com/servo/rust-url/issues/444 (remove rust-encoding support)
* [x] https://github.com/servo/rust-url/issues/455 (bump Rust version requirement)
* [ ] https://github.com/servo/rust-url/issues/460
* [ ] https://github.com/servo/rust-url/issues/462
* [x] #506
* [x] Remove everything marked as deprecated
* [x] Stop re-exporting entire crates, make crate dependencies private where possible
* [ ] Others?

## Behavior changes

Some of those might arguably be considered breaking. Or maybe not.

* [ ] https://github.com/servo/rust-url/issues/85
* [ ] https://github.com/servo/rust-url/issues/278
* [ ] https://github.com/servo/rust-url/issues/450
* [ ] https://github.com/servo/rust-url/issues/461
* [ ] https://github.com/servo/rust-url/issues/373
* [ ] https://github.com/servo/rust-url/issues/391
* [ ] https://github.com/servo/rust-url/pull/442

## Non-breaking changes

… maybe worth looking at while I’m spending time on rust-url:

* [x] Use rustfmt. The default style is probably more stable these days. CC https://github.com/servo/rust-url/issues/336
  - [ ]  Enforce it on CI?
* [ ] https://github.com/servo/rust-url/issues/383

## Unsure if breaking

* [ ] https://github.com/servo/rust-url/issues/348
* [ ] https://github.com/servo/rust-url/issues/359
* [ ] https://github.com/servo/rust-url/issues/363

# Potential breaking changes for the `idna` crate

* [x] https://github.com/servo/rust-url/issues/486
* [ ] Reconsider error handling, CC https://github.com/servo/rust-url/issues/359

# Potential breaking changes for the `percent_encoding` crate

* [x] Encode sets as `const` values of a single type, instead of types implementing a trait

**Comment by atouchet** [comment]
Servo is now using hyper 0.12.

**Comment by est31** [comment]
rustc-serialize should probably be put onto the list, too: #506

**Comment by killercup** [comment]
Hey, for an internal project we wanted to have a url crate with some of the things listed here. I forked this repo and made some changes, mostly removing rustc-serialize and adding serde 1.0, which you can find [here](https://github.com/killercup/earl). This is not meant to replace this crate, but to as soon as possible rexports all of url 2.0 and get deprecated :)

Are you okay with me publishing this fork to crates.io? We'll want to publish some crates depending on this.

**Comment by SimonSapin** [comment]
I mean, if publishing a fork is what you need to get other work unblocked I don’t really have a reason to stop you.

That said, Just Making `url` 2.0 Already is probably a better outcome. I’ve just been putting it off because the list above looks so daunting. But maybe you or other people can help. I’ve pushed a `2.0` branch which for now is the same as master. Feel free to make PRs into that branch for any of the above (or more). The changes your already have in your fork would be a good start.

The key is we don’t have to do *everything* in the list. While batching breaking changes is better to avoid the need to do 3.0 too soon, if no one has implemented a particular change after some time maybe it’s wasn’t that important in the first place.

**Comment by killercup** [comment]
> That said, Just Making url 2.0 Already is probably a better outcome.

Definitely.

> I’ve just been putting it off because the list above looks so daunting.

I can relate to that very much! And since url is a pretty major crate the barrier to just releasing a new major version is pretty high I imagine. 

I'm gonna publish my fork so our internal stuff can easily depend on it (and I so that I can feel like I did something this week). I'll probably also keep doing weird stuff there just to experiment with some APIs, and release a new version until I either hit 0.99.0 or am actually happy with the code.

I hope to have the time to slowly merge to "good" parts back into your 2.0 branch. Actually, anyone is welcome to just take my changes and merge them over!

**Comment by SimonSapin** [comment]
* https://crates.io/crates/url/2.0.0
* https://crates.io/crates/idna/0.2.0
* https://crates.io/crates/percent-encoding/2.0.0
