### ISSUE TITLE
Specification alignment tracking issue

### ISSUE THREAD

**Issue by crowlKats** [servo/rust-url#742]
updating wpt testdata makes following nonalignment evident:

- [ ] https://github.com/web-platform-tests/wpt/pull/32539
- [ ] https://github.com/whatwg/url/pull/589
- [ ] https://github.com/web-platform-tests/wpt/pull/25987
- [ ] https://github.com/whatwg/url/pull/544 (https://github.com/servo/rust-url/issues/642)
- [ ] https://github.com/web-platform-tests/wpt/pull/28432
- [ ] https://github.com/whatwg/url/pull/550
- [ ] https://github.com/whatwg/url/pull/505 (https://github.com/servo/rust-url/issues/601)
- [ ] https://github.com/whatwg/url/issues/539 (just testdata runner failure)
- [ ] https://github.com/whatwg/url/pull/619

**Comment by lucacasonato** [comment]
For some background on what this issue is:

We (the Deno project) use `rust-url` internally extensively. The crate is currently about 1.5 years out of sync with the spec. We are going to try to get it back up to 100% PASS in the next couple of weeks. The tenative plan of action is as follows:

1. Update the WPT testdata file in this repo with all of the new tests that still pass (#743).
2. Figure out which tests are blocked by which spec changes (we'll add that analysis to this issue).
3. Implement the relevant spec changes and add the corresponding tests. In some cases this may be as simple as updating the WPT test runner.
