### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lucacasonato** [servo/rust-url#850]
I think we need a bit of a roadmap to get the project back on track again. We're pretty out of date with WPT at this point, and CI is failing. I think the easiest way to get back on track is the following:

- [ ] Fix CI https://github.com/servo/rust-url/pull/849
- [ ] Fix the `no_std` support landed a few months ago and complete it, or revert it if it's not working
  - https://github.com/servo/rust-url/pull/843
- [ ] Improve WPT runner to support ignoring certain tests
- [ ] Update WPT files and disable all failing tests
- [ ] 

At that point we can figure out what the next steps should be

**Comment by valenting** [comment]
>  Improve WPT runner to support ignoring certain tests

I am quite happy with how the Gecko WPT runner works, and has an ini expectation file for known failures [example](https://searchfox.org/mozilla-central/source/testing/web-platform/meta/url/url-constructor.any.js.ini)
